<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../PzManager.Domain/PzManager.Domain.csproj" />
    <ProjectReference Include="../PzManager.Application/PzManager.Application.csproj" />
  </ItemGroup>
</Project>
